### ISSUE TITLE
HTTPS is broken

### ISSUE THREAD

**Issue by neheb** [libevent/libevent.github.com#2]
libevent.github.com redirects to libevent.org but the HTTPS certificate is for the pre-redirect.

GitHub supports HTTPS certificates for custom domains. See: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by azat** [comment]
> libevent.github.com redirects to libevent.org

There is no such redirect from https://libevent.github.com -> https://libevent.org, it redirects to http://libevent.org (note that I pasted protocols here)

Are you sure that you have http -> https redirect?
Maybe you just pressed on the icon in browser and it says that the connection is not secure?

> certificate is for the pre-redirect

This would be insane sir!

So yes libevent.org does not have any SSL certificate (but indeed it should).
So first we need to buy one.

**Comment by neheb** [comment]
You're right about the redirect. But you do not need a certificate. The link I showed demonstrates how you can get one for free.

**Comment by azat** [comment]
You mean let's encrypt? Yeah it is one of possibilities (but you have to update/automate it every 90 days)

**Comment by neheb** [comment]
Really? It sounds like GitHub handles that for you based on the blog post.

**Comment by azat** [comment]
Indeed, I will take a look

**Comment by azat** [comment]
Yep everything works after @nmathewson updated A records.
Thanks for the report!

But I guess it will take some time github to make redirects via https from libevent.github.io, so let's wait sometime.

**Comment by neheb** [comment]
Suboptimal, no HSTS. But I'll take it.

**Comment by azat** [comment]
> Suboptimal, no HSTS. But I'll take it
>
It is by intention. I decided not to turn it on right now.

>
